//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIserviciosV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDServicioV2EntitiesSTPR : DbContext
    {
        public BDServicioV2EntitiesSTPR()
            : base("name=BDServicioV2EntitiesSTPR")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_ListClient_Result> SP_ListClient_Result()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ListClient_Result>("SP_ListClient_Result");
        }
    
        public virtual ObjectResult<SP_DetailInvoice_Result> SP_DetailInvoice_Result(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DetailInvoice_Result>("SP_DetailInvoice_Result", idParameter);
        }
    
        public virtual ObjectResult<SP_Indicadores_Result> SP_Indicadores_Result()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Indicadores_Result>("SP_Indicadores_Result");
        }
    }
}
